Wiki: Remove Include macro
 - the funtionaltiy was broken and only resulted in tracebacks
   (see attached one below)
 - it is only used in old wiki-revisions on wiki.ubuntuusers.de.
   It is acceptable that an error is shown in old revisions.
 - iternal discussion: https://forum.ubuntuusers.de/topic/seiten-einbinden-noch-benoetigt/

example traceback in sentry was:

```
AttributeError: 'Text' object has no attribute 'render'
  File "celery/app/trace.py", line 760, in __protected_call__
    return self.run(*args, **kwargs)
  File "inyoka/wiki/tasks.py", line 125, in render_one_revision
    Revision.objects.get(id=revision_id).rendered_text[:100]
  File "inyoka/wiki/models.py", line 1318, in rendered_text
    return self.text.value_rendered
  File "inyoka/utils/database.py", line 228, in field_rendered
    return content_cache.get_or_set(key, create_content, self.redis_timeout)
  File "inyoka/utils/cache.py", line 166, in get_or_set
    value = self.client.encode(callback())
  File "inyoka/utils/database.py", line 324, in create_content
    return self.get_render_method()(
  File "inyoka/utils/database.py", line 295, in get_field_rendered
    return node.render(context, format='html')
  File "inyoka/markup/machine.py", line 67, in render
    return Renderer(self).render(context, format)
  File "inyoka/markup/machine.py", line 232, in render
    return ''.join(self.stream(context, format))
  File "inyoka/markup/machine.py", line 221, in stream
    yield instruction.render(context, format)
  File "inyoka/markup/macros.py", line 100, in render
    rv = self.build_node(context, format)
  File "inyoka/wiki/macros.py", line 262, in build_node
    return page.rev.text.render(context=context, format=format)
```