Fix taglist after python3 migration
Reported via https://forum.ubuntuusers.de/topic/tagliste-tagname-liefert-kein-ergebnis

The traceback seems to be missed with the migration to python3,
as the string-module has no lower-function anymore.
The fix just uses the builtin str instead of the string module
(str works on unicode in python3, too).

The simple added test has been previously failed with the following traceback:

ERROR: test_taglist (tests.apps.wiki.test_macros.TestWikiMacros)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/chris/Dev/inyoka/tests/apps/wiki/test_macros.py", line 37, in test_taglist
    format='html'
  File "/home/chris/Dev/inyoka/inyoka/markup/machine.py", line 68, in render
    return Renderer(self).render(context, format)
  File "/home/chris/Dev/inyoka/inyoka/markup/machine.py", line 234, in render
    return ''.join(self.stream(context, format))
  File "/home/chris/Dev/inyoka/inyoka/markup/machine.py", line 223, in stream
    yield instruction.render(context, format)
  File "/home/chris/Dev/inyoka/inyoka/markup/macros.py", line 101, in render
    rv = self.build_node(context, format)
  File "/home/chris/Dev/inyoka/inyoka/wiki/macros.py", line 209, in build_node
    for page in sorted(pages, key=string.lower):
AttributeError: module 'string' has no attribute 'lower'