Make django debug toolbar useable again
If statics are missing (f.e. no JS loaded) this can be fixed by
running a command like

```
python manage.py collectstatic --noinput --link
```

Traceback was

```
Traceback (most recent call last):
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/sentry_sdk/integrations/django/__init__.py", line 128, in sentry_patched_wsgi_handler
    environ, start_response
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/sentry_sdk/integrations/wsgi.py", line 140, in __call__
    reraise(*_capture_exception(hub))
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/sentry_sdk/_compat.py", line 54, in reraise
    raise value
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/sentry_sdk/integrations/wsgi.py", line 136, in __call__
    _sentry_start_response, start_response, transaction
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 141, in __call__
    response = self.get_response(request)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/sentry_sdk/integrations/django/__init__.py", line 361, in sentry_patched_get_response
    return old_get_response(self, request)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/core/handlers/base.py", line 75, in get_response
    response = self._middleware_chain(request)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/sentry_sdk/integrations/django/middleware.py", line 175, in __call__
    return f(*args, **kwargs)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/sentry_sdk/integrations/django/middleware.py", line 175, in __call__
    return f(*args, **kwargs)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/sentry_sdk/integrations/django/middleware.py", line 175, in __call__
    return f(*args, **kwargs)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/sentry_sdk/integrations/django/middleware.py", line 175, in __call__
    return f(*args, **kwargs)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/sentry_sdk/integrations/django/middleware.py", line 175, in __call__
    return f(*args, **kwargs)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/sentry_sdk/integrations/django/middleware.py", line 175, in __call__
    return f(*args, **kwargs)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/sentry_sdk/integrations/django/middleware.py", line 175, in __call__
    return f(*args, **kwargs)
  File "/home/chris/Dev/inyoka/inyoka/middlewares/tz.py", line 29, in __call__
    response = self.get_response(request)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/sentry_sdk/integrations/django/middleware.py", line 175, in __call__
    return f(*args, **kwargs)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/sentry_sdk/integrations/django/middleware.py", line 175, in __call__
    return f(*args, **kwargs)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/sentry_sdk/integrations/django/middleware.py", line 175, in __call__
    return f(*args, **kwargs)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/utils/deprecation.py", line 94, in __call__
    response = response or self.get_response(request)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/sentry_sdk/integrations/django/middleware.py", line 175, in __call__
    return f(*args, **kwargs)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/debug_toolbar/middleware.py", line 61, in __call__
    response = toolbar.process_request(request)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/debug_toolbar/panels/__init__.py", line 174, in process_request
    return self.get_response(request)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/debug_toolbar/panels/timer.py", line 58, in process_request
    return super().process_request(request)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/debug_toolbar/panels/__init__.py", line 174, in process_request
    return self.get_response(request)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/debug_toolbar/panels/__init__.py", line 174, in process_request
    return self.get_response(request)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/debug_toolbar/panels/headers.py", line 50, in process_request
    return super().process_request(request)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/debug_toolbar/panels/__init__.py", line 174, in process_request
    return self.get_response(request)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/debug_toolbar/panels/__init__.py", line 174, in process_request
    return self.get_response(request)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/debug_toolbar/panels/__init__.py", line 174, in process_request
    return self.get_response(request)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/debug_toolbar/panels/staticfiles.py", line 115, in process_request
    return super().process_request(request)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/debug_toolbar/panels/__init__.py", line 174, in process_request
    return self.get_response(request)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/debug_toolbar/panels/__init__.py", line 174, in process_request
    return self.get_response(request)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/debug_toolbar/panels/__init__.py", line 174, in process_request
    return self.get_response(request)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/debug_toolbar/panels/__init__.py", line 174, in process_request
    return self.get_response(request)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/debug_toolbar/panels/logging.py", line 77, in process_request
    return super().process_request(request)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/debug_toolbar/panels/__init__.py", line 174, in process_request
    return self.get_response(request)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/core/handlers/exception.py", line 36, in inner
    response = response_for_exception(request, exc)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/core/handlers/base.py", line 100, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/urls/resolvers.py", line 536, in resolve
    for pattern in self.url_patterns:
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/urls/resolvers.py", line 584, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/urls/resolvers.py", line 577, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/chris/.pyenv/versions/3.5.2/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import

  File "<frozen importlib._bootstrap>", line 969, in _find_and_load

  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 665, in exec_module

  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed

  File "/home/chris/Dev/inyoka/inyoka/wiki/urls.py", line 14, in <module>
    from . import actions, views
  File "/home/chris/Dev/inyoka/inyoka/wiki/actions.py", line 46, in <module>
    from inyoka.wiki.forms import (
  File "/home/chris/Dev/inyoka/inyoka/wiki/forms.py", line 99, in <module>
    class PageEditForm(SurgeProtectionMixin, forms.Form):
  File "/home/chris/Dev/inyoka/inyoka/wiki/forms.py", line 123, in PageEditForm
    help_text=storage['wiki_edit_note_rendered'])
  File "/home/chris/Dev/inyoka/inyoka/utils/storage.py", line 89, in __getitem__
    return self.get(key)
  File "/home/chris/Dev/inyoka/inyoka/utils/storage.py", line 25, in get
    value = cache.get('storage/{}'.format(key))
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/debug_toolbar/panels/cache.py", line 49, in wrapped
    backend=self.cache,
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/debug_toolbar/panels/cache.py", line 206, in _store_call_info
    "trace": render_stacktrace(trace),
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/debug_toolbar/utils.py", line 88, in render_stacktrace
    "show_locals": dt_settings.get_config()["ENABLE_STACKTRACES_LOCALS"],
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/template/loaders/base.py", line 18, in get_template
    for origin in self.get_template_sources(template_name):
  File "/home/chris/Dev/inyoka/inyoka/utils/templating.py", line 216, in get_template_sources
    return super(DjangoLoader, self).get_template_sources(template_name, skip)
TypeError: get_template_sources() takes 2 positional arguments but 3 were given
```