Bump feedparser to 6.0.0b3
Even if it's a beta, it prevents the following traceback:

[2020-05-11 01:53:06,624] DEBUG:inyoka:  synced entry '2382@https://hyperblog.de/'
[2020-05-11 01:53:06,630] DEBUG:inyoka: syncing blog Demystifikation
[2020-05-11 01:53:07,140] ERROR:inyoka: Celery job exception: RuntimeError (generator raised StopIteration)
Traceback (most recent call last):
  File "/home/chris/.venvs/inyoka3/lib/python3.8/site-packages/feedparser.py", line 3766, in _gen_georss_coords
    t = [nxt(), nxt()][::swap and -1 or 1]
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chris/.venvs/inyoka3/lib/python3.8/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/chris/.venvs/inyoka3/lib/python3.8/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/chris/Dev/inyoka/inyoka/planet/tasks.py", line 71, in sync
    feed = feedparser.parse(blog.feed_url)
  File "/home/chris/.venvs/inyoka3/lib/python3.8/site-packages/feedparser.py", line 3956, in parse
    saxparser.parse(source)
  File "/usr/lib/python3.8/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python3.8/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/lib/python3.8/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "/build/python/src/Python-3.8.2/Modules/pyexpat.c", line 459, in EndElement
  File "/usr/lib/python3.8/xml/sax/expatreader.py", line 381, in end_element_ns

  File "/home/chris/Dev/inyoka/inyoka/planet/tasks.py", line 71, in sync
    feed = feedparser.parse(blog.feed_url)
  File "/home/chris/.venvs/inyoka3/lib/python3.8/site-packages/feedparser.py", line 3956, in parse
    saxparser.parse(source)
  File "/usr/lib/python3.8/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python3.8/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/lib/python3.8/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "/build/python/src/Python-3.8.2/Modules/pyexpat.c", line 459, in EndElement
  File "/usr/lib/python3.8/xml/sax/expatreader.py", line 381, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/chris/.venvs/inyoka3/lib/python3.8/site-packages/feedparser.py", line 2052, in endElementNS
    self.unknown_endtag(localname)
  File "/home/chris/.venvs/inyoka3/lib/python3.8/site-packages/feedparser.py", line 696, in unknown_endtag
    method()
  File "/home/chris/.venvs/inyoka3/lib/python3.8/site-packages/feedparser.py", line 1463, in _end_georss_point
    geometry = _parse_georss_point(self.pop('geometry'))
  File "/home/chris/.venvs/inyoka3/lib/python3.8/site-packages/feedparser.py", line 3775, in _parse_georss_point
    coords = list(_gen_georss_coords(value, swap, dims))
RuntimeError: generator raised StopIteration
[2020-05-11 01:53:07,140] ERROR:celery.app.trace: Task inyoka.planet.tasks.sync[b83bad5d-9663-4e78-b7cd-640133ca7dc2] raised unexpected: RuntimeError('generator raised StopIteration')
Traceback (most recent call last):
  File "/home/chris/.venvs/inyoka3/lib/python3.8/site-packages/feedparser.py", line 3766, in _gen_georss_coords
    t = [nxt(), nxt()][::swap and -1 or 1]
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chris/.venvs/inyoka3/lib/python3.8/site-packages/celery/app/trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/home/chris/.venvs/inyoka3/lib/python3.8/site-packages/celery/app/trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "/home/chris/Dev/inyoka/inyoka/planet/tasks.py", line 71, in sync
    feed = feedparser.parse(blog.feed_url)
  File "/home/chris/.venvs/inyoka3/lib/python3.8/site-packages/feedparser.py", line 3956, in parse
    saxparser.parse(source)
  File "/usr/lib/python3.8/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python3.8/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/lib/python3.8/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
  File "/build/python/src/Python-3.8.2/Modules/pyexpat.c", line 459, in EndElement
  File "/usr/lib/python3.8/xml/sax/expatreader.py", line 381, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/home/chris/.venvs/inyoka3/lib/python3.8/site-packages/feedparser.py", line 2052, in endElementNS
    self.unknown_endtag(localname)
  File "/home/chris/.venvs/inyoka3/lib/python3.8/site-packages/feedparser.py", line 696, in unknown_endtag
    method()
  File "/home/chris/.venvs/inyoka3/lib/python3.8/site-packages/feedparser.py", line 1463, in _end_georss_point
    geometry = _parse_georss_point(self.pop('geometry'))
  File "/home/chris/.venvs/inyoka3/lib/python3.8/site-packages/feedparser.py", line 3775, in _parse_georss_point
    coords = list(_gen_georss_coords(value, swap, dims))
RuntimeError: generator raised StopIteration