Fix KeyError for password in LoginForm
 - Always require a password
 - Removed logic for http usernames that seemed to be relevent
   when OpenID was available.

Previously, omitting the password in a POST resulted in an error:

```
KeyError: 'password'
  File "django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "inyoka/utils/http.py", line 40, in proxy
    rv = f(request, *args, **kwargs)
  File "inyoka/portal/views.py", line 366, in login
    if form.is_valid():
  File "django/forms/forms.py", line 175, in is_valid
    return self.is_bound and not self.errors
  File "django/forms/forms.py", line 170, in errors
    self.full_clean()
  File "django/forms/forms.py", line 373, in full_clean
    self._clean_form()
  File "django/forms/forms.py", line 400, in _clean_form
    cleaned_data = self.clean()
  File "inyoka/portal/forms.py", line 106, in clean
    data['password'] == ''):
```