Update dependencies
django to 2.2.24
gunicorn to 20.1.0
lxml to 4.6.3
pygments to 2.9.0
urllib3 to 1.26.5

Fixed an error in tests that seems to be caused by the traversal fix in django.
https://docs.djangoproject.com/en/2.2/releases/2.2.24/

======================================================================
ERROR: test_edit_post_remove_attachments (tests.apps.forum.test_views.TestPostEditView)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/chris/Dev/inyoka/tests/apps/forum/test_views.py", line 1191, in test_edit_post_remove_attachments
    att1 = Attachment.objects.create(name=TEST_ATTACHMENT1, file=File(f), mimetype='image/png', post=post)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/db/models/query.py", line 422, in create
    obj.save(force_insert=True, using=self.db)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/db/models/base.py", line 744, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/db/models/base.py", line 782, in save_base
    force_update, using, update_fields,
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/db/models/base.py", line 873, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/db/models/base.py", line 911, in _do_insert
    using=using, raw=raw)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1376, in execute_sql
    for sql, params in self.as_sql():
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1320, in as_sql
    for obj in self.query.objs
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1320, in <listcomp>
    for obj in self.query.objs
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1319, in <listcomp>
    [self.prepare_value(field, self.pre_save_val(field, obj)) for field in fields]
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1270, in pre_save_val
    return field.pre_save(obj, add=True)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/db/models/fields/files.py", line 289, in pre_save
    file.save(file.name, file.file, save=False)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/db/models/fields/files.py", line 87, in save
    name = self.field.generate_filename(self.instance, name)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/db/models/fields/files.py", line 308, in generate_filename
    filename = validate_file_name(filename, allow_relative_path=True)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/core/files/utils.py", line 19, in validate_file_name
    "Detected path traversal attempt in '%s'" % name
django.core.exceptions.SuspiciousFileOperation: Detected path traversal attempt in '/home/chris/Dev/inyoka/inyoka/media/forum/attachments/00/00/test_attachment.png'