Make Ikhaya service robuster
Eliminate some lines where an exception could occur.
Instead return a errors via HTTP-status-codes.
Traceback in sentry for missing check of post-keys was

```
KeyError: 'username'
  File "django/utils/datastructures.py", line 76, in __getitem__
    list_ = super().__getitem__(key)

MultiValueDictKeyError: 'username'
  File "django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "django/utils/deprecation.py", line 116, in __call__
    response = self.process_request(request)
  File "inyoka/middlewares/services.py", line 40, in process_request
    response = call(request, parts[1])
  File "inyoka/utils/services.py", line 33, in __call__
    return self.methods[name](request)
  File "inyoka/ikhaya/services.py", line 22, in change_suggestion_assignment
    username, suggestion = post['username'], post['suggestion']
  File "django/utils/datastructures.py", line 78, in __getitem__
    raise MultiValueDictKeyError(key)
```