Wiki, `TestPage.test_update_related_pages__content_updated`: Simplify case
Sometimes the test failed due to the self link being marked as missing.
This is not related to the objective of the test.
Thus, remove the link in the example markup.

Traceback in CI was f.e.:

```
Traceback (most recent call last):
  File "/home/runner/work/inyoka-pub/inyoka-pub/tests/apps/wiki/test_models.py", line 29, in test_update_related_pages__content_updated
    self.assertEqual(page.last_rev.text.value_rendered,
AssertionError: '<p><[39 chars]080/test1/" class="internal missing">test1</a> content Foo</p>' != '<p><[39 chars]080/test1/" class="internal">test1</a> content Foo</p>'
- <p><a href="http://wiki.ubuntuusers.local:8080/test1/" class="internal missing">test1</a> content Foo</p>
?                                                                       --------
+ <p><a href="http://wiki.ubuntuusers.local:8080/test1/" class="internal">test1</a> content Foo</p>
```