Privmsg: Fix UnboundLocalError with invalid action
Instead of trying to show a msg, if the action is invalid,
raise a HTTP 404.

Trace in sentry was
```
Traceback (most recent call last):
  File "django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "django/contrib/auth/decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "inyoka/utils/http.py", line 38, in proxy
    rv = f(request, *args, **kwargs)
  File "inyoka/portal/views.py", line 968, in privmsg
    'message': msg,
UnboundLocalError: cannot access local variable 'msg' where it is not associated with a value
```