Use AnonymousUser for bad request template to avoid an exception
The request object can miss a user attribute.
Always use AnonymousUser, so the jinja templates can be rendered.

trace in sentry was

```
MultiPartParserError: Invalid boundary in multipart: None
  File "django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "django/utils/deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "inyoka/middlewares/common.py", line 68, in process_request
    new_post = request.POST.copy()
  File "django/core/handlers/wsgi.py", line 93, in _get_post
    self._load_post_and_files()
  File "django/http/request.py", line 373, in _load_post_and_files
    self._post, self._files = self.parse_file_upload(self.META, data)
  File "django/http/request.py", line 320, in parse_file_upload
    parser = MultiPartParser(META, post_data, self.upload_handlers, self.encoding)
  File "django/http/multipartparser.py", line 87, in __init__
    raise MultiPartParserError(

AttributeError: 'WSGIRequest' object has no attribute 'user'
  File "django/core/handlers/exception.py", line 164, in get_exception_response
    response = callback(request, exception=exception)
  File "inyoka/utils/http.py", line 76, in bad_request_view
    return render(request, 'errors/400.html', {'request': request}, status=400)
  File "django/shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "django/template/backends/jinja2.py", line 72, in render
    context.update(context_processor(request))
  File "inyoka/utils/templating.py", line 47, in context_data
    user = request.user
```