User.icon add recursive=True
traceback was

```
======================================================================
ERROR: tests.apps.portal.test_views (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.apps.portal.test_views
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/opt/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/runner/work/inyoka/inyoka/tests/apps/portal/test_views.py", line 32, in <module>
    from inyoka.portal.views import static_page
  File "/home/runner/work/inyoka/inyoka/inyoka/portal/views.py", line 43, in <module>
    from inyoka.portal.forms import (
  File "/home/runner/work/inyoka/inyoka/inyoka/portal/forms.py", line 413, in <module>
    class EditUserProfileForm(UserCPProfileForm):
  File "/home/runner/venv/lib/python3.5/site-packages/django/forms/models.py", line 256, in __new__
    apply_limit_choices_to=False,
  File "/home/runner/venv/lib/python3.5/site-packages/django/forms/models.py", line 172, in fields_for_model
    formfield = f.formfield(**kwargs)
  File "/home/runner/venv/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 1725, in formfield
    **kwargs,
  File "/home/runner/venv/lib/python3.5/site-packages/django/db/models/fields/__init__.py", line 897, in formfield
    return form_class(**defaults)
  File "/home/runner/venv/lib/python3.5/site-packages/django/forms/fields.py", line 1109, in __init__
    for f in os.scandir(self.path):
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/work/inyoka/inyoka/inyoka/media/portal/team_icons'
```

The semantic change was introduced in
https://github.com/django/django/commit/a0ca4b5694f43c63ea13ba6908eff2bd53ee7ebb

The fix to add recursive is more a workaround, as it will use another
codepath in django. In this codepath no exception is raised, if the folder
does not exist in the file system. In this context the recursive-parameter
should not make any difference in the real world, as this folder does
not contain any subfolders.

Furthermore, the folder is created via a migration, if it does not
exist, yet.