Defer user.forum_read_status, as it can not be pickled
user.forum_read_status is a BinaryField which postgres
returns as a memoryview. A memoryview-type can not be pickled.
However, if memoryview is casted to a bytes, it can be pickled.
Neverthelesse adapoting the serialization process of django redis seem
not trivial (but is possible via https://github.com/jazzband/django-redis/blob/master/docs/index.rst#pluggable-serializer).

As a workaround the forum_read_status fields are defered, so the Model-
instances can be pickled again. Furthermore, the forum_read_status seems
to be not used, so this also will not generated an extra query.

reproduciable on `python mange.py shell` via

```
import pickle
from inyoka.wiki.models import Revision
# fails
pickle.dumps(Revision.objects.select_related('text', 'page', 'user').filter(page__name__iexact='audacious').latest())

# the next one succeeds
pickle.dumps(Revision.objects.select_related('text').latest())
```


Traceback was like

ERROR [0.021s]: test_get_by_name_cache_case_sensitive_set (tests.apps.wiki.test_models.TestPageManager)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/chris/Dev/inyoka/tests/apps/wiki/test_models.py", line 25, in test_get_by_name_cache_case_sensitive_set
    Page.objects.get_by_name('Test')
  File "/home/chris/Dev/inyoka/inyoka/wiki/models.py", line 424, in get_by_name
    cache.set(cache_key, rev, cachetime)
  File "/home/chris/.venvs/inyoka3/lib/python3.8/site-packages/django_redis/cache.py", line 32, in _decorator
    return method(self, *args, **kwargs)
  File "/home/chris/.venvs/inyoka3/lib/python3.8/site-packages/django_redis/cache.py", line 67, in set
    return self.client.set(*args, **kwargs)
  File "/home/chris/.venvs/inyoka3/lib/python3.8/site-packages/django_redis/client/default.py", line 111, in set
    nvalue = self.encode(value)
  File "/home/chris/.venvs/inyoka3/lib/python3.8/site-packages/django_redis/client/default.py", line 323, in encode
    value = self._serializer.dumps(value)
  File "/home/chris/.venvs/inyoka3/lib/python3.8/site-packages/django_redis/serializers/pickle.py", line 21, in dumps
    return pickle.dumps(value, self._pickle_version)
TypeError: cannot pickle 'memoryview' object