Migrate jabbberbot from NoArgsCommand to BaseCommand
NoArgsCommand was removed, see
https://github.com/django/django/commit/b4002a214399d8619965f40e153ca3f7dcb20904

Without this change
$ python manage.py jabberbot --help

resulted in

ImportError: cannot import name 'NoArgsCommand' from 'django.core.management.base' (/home/chris/.venvs/inyoka3/lib/python3.8/site-packages/django/core/management/base.py)