Comparison of EmptyQuerySet with isinstance does not work.
Error message:
File ".../inyoka/envs/django-v1.6/local/lib/python2.7/site-packages/django/db/models/query.py", line 918, in __instancecheck__
    return instance.query.is_empty()
AttributeError: type object 'EmptyQuerySet' has no attribute 'query'

@Markush2010: Is this ok for you?

Conflicts:
	inyoka/forum/acl.py