BDD Test: Forcefully close DB sessions
Otherwise the DB can not be destroyed after the tests ran.
Error was like
```
$ DJANGO_SETTINGS_MODULE='tests.bdd.settings.headless' python -m behave -f allure_behave.formatter:AllureFormatter -o allure-results --tags=-skip tests/bdd/password_forgotten.feature
Creating test database for alias 'default'...
Destroying test database for alias 'default'...
CLEANUP-ERROR in cleanup_fixture: OperationalError: FEHLER:  auf Datenbank »test_bdd_1720c72a-039f-11ec-83f3-0800270af1fc« wird von anderen Benutzern zugegriffen
DETAIL:  14 andere Sitzungen verwenden die Datenbank.

Traceback (most recent call last):
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
psycopg2.errors.ObjectInUse: FEHLER:  auf Datenbank »test_bdd_1720c72a-039f-11ec-83f3-0800270af1fc« wird von anderen Benutzern zugegriffen
DETAIL:  14 andere Sitzungen verwenden die Datenbank.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/behave/runner.py", line 222, in _do_cleanups
    cleanup_func()
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/behave/fixture.py", line 162, in cleanup_fixture
    next(func_it)           # CLEANUP-FIXTURE PART
  File "/home/chris/Dev/inyoka/tests/bdd/behave_fixtures.py", line 19, in django_test_runner
    context.test_runner.teardown_databases(context.old_db_config)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/test/runner.py", line 583, in teardown_databases
    keepdb=self.keepdb,
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/test/utils.py", line 299, in teardown_databases
    connection.creation.destroy_test_db(old_name, verbosity, keepdb)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/db/backends/base/creation.py", line 259, in destroy_test_db
    self._destroy_test_db(test_database_name, verbosity)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/db/backends/base/creation.py", line 276, in _destroy_test_db
    % self.connection.ops.quote_name(test_database_name))
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/sentry_sdk/integrations/django/__init__.py", line 500, in execute
    return real_execute(self, sql, params)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/chris/Dev/inyoka/venv3.5.2/lib/python3.5/site-packages/django/db/backends/utils.py", line 82, in _execute
    return self.cursor.execute(sql)
django.db.utils.OperationalError: FEHLER:  auf Datenbank »test_bdd_1720c72a-039f-11ec-83f3-0800270af1fc« wird von anderen Benutzern zugegriffen
DETAIL:  14 andere Sitzungen verwenden die Datenbank.

1 feature passed, 0 failed, 0 skipped
2 scenarios passed, 0 failed, 1 skipped
4 steps passed, 0 failed, 3 skipped, 0 undefined
Took 0m0.923s
```